#!/bin/bash

set -ueo pipefail

IVY_DEFAULT_VERSION="${IVY_DEFAULT_VERSION:-2.4.0}"
IVY_HOME="${IVY_HOME:-}"

if [[ -z "${IVY_HOME}" && -z "${IVY_DEFAULT_VERSION}" ]]; then
  echo "IVY_HOME must be set if there is no IVY_DEFAULT_VERSION"
  exit 1;
fi

if [[ -z "${IVY_HOME}" ]]; then
    IVY_HOME="${HOME}/.ivy2"
    if [[ ! -f "${IVY_HOME}/ivy-${IVY_DEFAULT_VERSION}.jar" ]]; then
        mkdir -p "${IVY_HOME}"
        cd "${IVY_HOME}"
        curl -s -O "https://prezidevrepo.s3.amazonaws.com/jars/ivy-${IVY_DEFAULT_VERSION}.jar"
        cd - &>/dev/null
    fi
fi

IVY_JAR=$(if [[ -f "${IVY_HOME}" ]]; then
    printf "${IVY_HOME}"
else
    ls "${IVY_HOME}/"*ivy*.jar | head -n 1
fi)

# extract -D command line arguments to dedicated list of properties
# Java expects -D arguments before Main declaration

typeset -a properties=()
typeset -a arguments=()

JAVA_PROPERTY_REGEX='^-D(.*)+=(.*)+$'

for argument in "$@"; do
	if [[ "$argument" =~ $JAVA_PROPERTY_REGEX ]]; then
		properties+=($argument)
	else
		arguments+=($argument)
	fi
done

exec java "${properties[@]-}" -jar "${IVY_JAR}" "${arguments[@]-}"
