#!/bin/bash

if [[ -z "${IVY_HOME}" ]]; then
  echo "IVY_HOME must be set"
  exit 1;
fi

pushd $IVY_HOME >> /dev/null
IVY_JAR=$(find *ivy*.jar)
popd >> /dev/null

java -jar ${IVY_HOME}/${IVY_JAR} $@
exit $?
